export const ASYNC_LOAD_INQUIRIES_LIST = 'ASYNC_LOAD_INQUIRIES_LIST';
export const ASYNC_LOAD_CATEGORIES = 'ASYNC_LOAD_CATEGORIES';
export const ASYNC_DELETE_INQUIRY = 'ASYNC_DELETE_INQUIRY';
export const SYNC_INQUIRIES_LIST_SEARCH_PARAMS = 'SYNC_INQUIRIES_LIST_SEARCH_PARAMS';
