export const ASYNC_LOAD_PROVIDES_LIST = 'ASYNC_LOAD_PROVIDES_LIST';
export const ASYNC_DELETE_PROVIDE = 'ASYNC_DELETE_PROVIDE';
export const SYNC_PROVIDES_LIST_SEARCH_PARAMS = 'SYNC_PROVIDES_LIST_SEARCH_PARAMS';
