export const ASYNC_LOAD_USER_GROUP_LIST = 'ASYNC_LOAD_USER_GROUP_LIST';
export const ASYNC_CREATE_USER_GROUP = 'ASYNC_CREATE_USER_GROUP';
export const ASYNC_UPDATE_USER_GROUP = 'ASYNC_UPDATE_USER_GROUP';
export const ASYNC_DELETE_USER_GROUP = 'ASYNC_DELETE_USER_GROUP';
export const ASYNC_USER_GROUP_DETAILS = 'ASYNC_USER_GROUP_DETAILS';
export const SYNC_CLEAR_USER_GROUP_DETAILS = 'SYNC_CLEAR_USER_GROUP_DETAILS';
