export const ASYNC_LOAD_MATERIALS_LIST = 'ASYNC_LOAD_MATERIALS_LIST';
export const ASYNC_DELETE_MATERIAL = 'ASYNC_DELETE_MATERIAL';
export const SYNC_MATERIALS_LIST_SEARCH_PARAMS = 'SYNC_MATERIALS_LIST_SEARCH_PARAMS';
