export const ASYNC_LOAD_MATERIALS_LIST = 'ASYNC_LOAD_MATERIALS_LIST';
export const ASYNC_DELETE_MATERIAL = 'ASYNC_DELETE_MATERIAL';
export const SYNC_MATERIALS_LIST_SEARCH_PARAMS = 'SYNC_MATERIALS_LIST_SEARCH_PARAMS';
export const ASYNC_GET_MATERIAL = 'ASYNC_GET_MATERIAL';
export const ASYNC_ADD_MATERIAL = 'ASYNC_ADD_MATERIAL';
export const ASYNC_EDIT_MATERIAL = 'ASYNC_EDIT_MATERIAL';
export const AYSNC_LOAD_CATEGORIES = 'AYSNC_LOAD_CATEGORIES';
