export const SEARCH_USER = 'SEARCH_USER';
export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const ASYNC_GET_ASSOCIATED_USER = 'ASYNC_GET_ASSOCIATED_USER';
export const ASYNC_SAVE_ASSOCIATED_USER = 'ASYNC_SAVE_ASSOCIATED_USER';
