export const ASYNC_LOAD_TRAINING_LIST = 'ASYNC_LOAD_TRAINING_LIST';
export const ASYNC_CREATE_TRAINING = 'ASYNC_CREATE_TRAINING';
export const ASYNC_UPDATE_TRAINING = 'ASYNC_UPDATE_TRAINING';
export const ASYNC_DELETE_TRAINING = 'ASYNC_DELETE_TRAINING';

export const SYNC_TRAINING_LIST_SEARCH_PARAMS = 'SYNC_TRAINING_LIST_SEARCH_PARAMS';
