export const ASYNC_LOAD_TRAINING_LIST = 'ASYNC_LOAD_TRAINING_LIST';
export const ASYNC_LOAD_TRAINING_USER_LIST = 'ASYNC_LOAD_TRAINING_USER_LIST';
export const ASYNC_CREATE_TRAINING = 'ASYNC_CREATE_TRAINING';
export const ASYNC_UPDATE_TRAINING = 'ASYNC_UPDATE_TRAINING';
export const ASYNC_DELETE_TRAINING = 'ASYNC_DELETE_TRAINING';
export const ASYNC_PUBLISH_TRAINING = 'ASYNC_PUBLISH_TRAINING';
export const ASYNC_CLOSE_TRAINING = 'ASYNC_CLOSE_TRAINING';
export const ASYNC_TRAINING_COURSE_DIRECTIONS = 'ASYNC_TRAINING_COURSE_DIRECTIONS';
export const ASYNC_LOAD_TRAINING_ASSOCIATIONS = 'ASYNC_LOAD_TRAINING_ASSOCIATIONS';
export const ASYNC_LOAD_TRAINING_DETAILS = 'ASYNC_LOAD_TRAINING_DETAILS';
export const ASYNC_SAVE_TRAINING_LESSON = 'ASYNC_SAVE_TRAINING_LESSON';
export const ASYNC_DELETE_TRAINING_LESSON = 'ASYNC_DELETE_TRAINING_LESSON';
export const ASYNC_UPDATE_TRAINING_LESSON = 'ASYNC_UPDATE_TRAINING_LESSON';
export const ASYNC_CHECK_IN_TRAINING_USER = 'ASYNC_CHECK_IN_TRAINING_USER';
export const ASYNC_LOAD_TRAINING_LESSON_DETAILS = 'ASYNC_LOAD_TRAINING_LESSON_DETAILS';

export const SYNC_TRAINING_LIST_SEARCH_PARAMS = 'SYNC_TRAINING_LIST_SEARCH_PARAMS';
export const SYNC_RESET_TRAININGS = 'SYNC_RESET_TRAININGS';
