export const LOAD_ONLINE_LESSONS_LIST = 'LOAD_ONLINE_LESSONS_LIST';
export const LOAD_ONLINE_LESSONS_CATEGORIES = 'LOAD_ONLINE_LESSONS_CATEGORIES';
export const CREATE_INITIAL_ONLINE_LESSONS = 'CREATE_INITIAL_ONLINE_LESSONS';
export const SYNC_ONLINE_LESSONS_SEARCH_PARAMS = 'LOAD_ONLINE_LESSONS_SEARCH_PARAMS';
export const SYNC_RESET_INITIAL_ONLINE_LESSONS = 'SYNC_RESET_INITIAL_ONLINE_LESSONS';
export const ASYNC_CREATE_CHAPTERS = 'ASYNC_CREATE_CHAPTERS';
export const ASYNC_CREATE_SECTIONS = 'ASYNC_CREATE_SECTIONS';
export const ASYNC_CREATE_POINTS = 'ASYNC_CREATE_POINTS';
export const ASYNC_REMOVE_POINTS = 'ASYNC_REMOVE_POINTS';
export const ASYNC_REMOVE_COURSE = 'ASYNC_REMOVE_COURSE';
export const ASYNC_SHELVE_COURSE = 'ASYNC_SHELVE_COURSE';
export const ASYNC_UNSHELVE_COURSE = 'ASYNC_UNSHELVE_COURSE';
export const ASYNC_LOAD_ONLINE_LESSON_DETAILS = 'ASYNC_LOAD_ONLINE_LESSON_DETAILS';

