export const LOAD_ONLINE_LESSONS_LIST = 'LOAD_ONLINE_LESSONS_LIST';
export const CREATE_INITIAL_ONLINE_LESSONS = 'CREATE_INITIAL_ONLINE_LESSONS';
export const SYNC_ONLINE_LESSONS_SEARCH_PARAMS = 'LOAD_ONLINE_LESSONS_SEARCH_PARAMS';
export const SYNC_CREATE_CHAPTERS = 'SYNC_CREATE_CHAPTERS';
export const SYNC_CREATE_SECTIONS = 'SYNC_CREATE_SECTIONS';
export const ASYNC_CREATE_POINTS = 'ASYNC_CREATE_POINTS';
