export const ASYNC_LOAD_ADMIN_LIST = 'ASYNC_LOAD_ADMIN_LIST';
export const ASYNC_CREATE_ADMIN = 'ASYNC_CREATE_ACCOUNT';
export const ASYNC_UPDATE_ADMIN = 'ASYNC_UPDATE_ACCOUNT';
export const ASYNC_DELETE_ADMIN = 'ASYNC_DELETE_ACCOUNT';
export const ASYNC_RESET_ADMIN_PASSWORD = 'ASYNC_RESET_ACCOUNT_PASSWORD';
export const SYNC_EDIT_ADMIN = 'SYNC_EDIT_ADMIN';
export const ASYNC_UPDATE_ADMIN_PERMISSIONS = 'ASYNC_UPDATE_ACCOUNT_PERMISSIONS';
export const ASYNC_LOAD_ADMIN_PERMISSIONS = 'ASYNC_LOAD_ACCOUNT_PERMISSIONS';
