export const ASYNC_LOAD_USER_LIST = 'LOAD_USER_LIST';
export const ASYNC_CREATE_USER = 'CREATE_USER';
export const ASYNC_DELETE_USER = 'AYNC_DELETE_USER';
export const SYNC_USER_LIST_SEARCH_PARAMS = 'SYNC_USER_LIST_SEARCH_PARAMS';
