export const ASYNC_LOAD_USER_LIST = 'LOAD_USER_LIST';
export const ASYNC_CREATE_USER = 'ASYNC_CREATE_USER';
export const ASYNC_UPDATE_USER = 'ASYNC_UPDATE_USER';
export const ASYNC_DELETE_USER = 'ASYNC_DELETE_USER';
export const ASYNC_LOAD_USERS_ASSOCIATIONS = 'ASYNC_LOAD_USERS_ASSOCIATIONS';
export const ASYNC_USER_DETAILS = 'ASYNC_USER_DETAILS';
export const ASYNC_RESET_ADMIN_PASSWORD = 'ASYNC_RESET_ADMIN_PASSWORD';

export const SYNC_USER_LIST_SEARCH_PARAMS = 'SYNC_USER_LIST_SEARCH_PARAMS';
