export const ASYNC_LOAD_EXAM_LIST = 'ASYNC_LOAD_EXAM_LIST';
export const ASYNC_DELETE_EXAM = 'ASYNC_DELETE_EXAM';
export const ASYNC_LOAD_CATEGORIES = 'ASYNC_LOAD_CATEGORIES';
export const ASYNC_CREATE_EXAM = 'ASYNC_CREATE_EXAM';
export const ASYNC_LOAD_EDIT_EXAM = 'ASYNC_LOAD_EDIT_EXAM';
export const ASYNC_UPDATE_EXAM = 'ASYNC_UPDATE_EXAM';
export const ASYNC_IMPORT_EXAM = 'ASYNC_IMPORT_EXAM';

export const SYNC_EXAM_LIST_SEARCH_PARAMS = 'SYNC_EXAM_LIST_SEARCH_PARAMS';
export const SYNC_RESET_EDIT_EXAM = 'SYNC_RESET_EDIT_EXAM';
