export const ASYNC_LOAD_LIST = 'ASYNC_LOAD_LIST';
export const ASYNC_CREATE_SECRET_LEVEL = 'ASYNC_CREATE_SECRET_LEVEL';
export const ASYNC_DELETE_TYPE = 'ASYNC_DELETE_TYPE';
export const ASYNC_DIC_TYPE_DETAILS = 'ASYNC_DIC_TYPE_DETAILS';
