export const ASYNC_LOAD_LIST = 'ASYNC_LOAD_LIST';
export const ASYNC_CREATE_SECRET_LEVEL = 'ASYNC_CREATE_SECRET_LEVEL';
export const ASYNC_EDIT_SECRET_LEVEL = 'ASYNC_EDIT_SECRET_LEVEL';
export const ASYNC_DELETE_TYPE = 'ASYNC_DELETE_TYPE';
export const ASYNC_DIC_TYPE_DETAILS = 'ASYNC_DIC_TYPE_DETAILS';
export const ASYNC_CREATE_SLIDERS = 'ASYNC_CREATE_SLIDERS';
export const ASYNC_GET_SLIDERS = 'ASYNC_GET_SLIDERS';
export const SYNC_RESET_SLIDERS = 'SYNC_RESET_SLIDERS';
