export const ASYNC_LOAD_TASKS_LIST = 'ASYNC_LOAD_TASKS_LIST';
export const ASYNC_CREATE_TASK = 'ASYNC_CREATE_TASK';
export const ASYNC_UPDATE_TASK = 'ASYNC_UPDATE_TASK';
export const ASYNC_DELETE_TASK = 'ASYNC_DELETE_TASK';
export const ASYNC_LOAD_DIRECTIONS = 'ASYNC_LOAD_DIRECTIONS';
export const ASYNC_LOAD_RELATED_LESSONS = 'ASYNC_LOAD_RELATED_LESSONS';
export const ASYNC_LOAD_RELATED_ONLINELESSONS = 'ASYNC_LOAD_RELATED_ONLINELESSONS';
export const ASYNC_LOAD_RELATED_ONECLICK = 'ASYNC_LOAD_RELATED_ONECLICK';
export const ASYNC_TASK_ASSOCIATIONS = 'ASYNC_TASK_ASSOCIATIONS';
export const ASYNC_LOAD_TASK_DETAILS = 'ASYNC_LOAD_TASK_DETAILS';
export const ASYNC_LOAD_CATEGORIES = 'ASYNC_LOAD_CATEGORIES';
export const ASYNC_SAVE_TASK_LESSONS = 'ASYNC_SAVE_TASK_LESSONS';

export const SYNC_RESET_TASK = 'SYNC_RESET_TASK';
export const SYNC_SEARCH_PARAMS = 'SYNC_SEARCH_PARAMS';
export const SYNC_SELECTED_LESSONS = 'SYNC_SELECTED_LESSONS';

