export const ASYNC_LOAD_TASKS_LIST = 'ASYNC_LOAD_TASKS_LIST';
export const ASYNC_CREATE_TASK = 'ASYNC_CREATE_TASK';
export const ASYNC_UPDATE_TASK = 'ASYNC_UPDATE_TASK';
export const ASYNC_DELETE_TASK = 'ASYNC_DELETE_TASK';
export const ASYNC_LOAD_DIRECTIONS = 'ASYNC_LOAD_DIRECTIONS';
export const ASYNC_LOAD_COURSES = 'ASYNC_LOAD_COURSES';
export const ASYNC_LOAD_PEDIAS = 'ASYNC_LOAD_PEDIAS';
