export const ASYNC_LOAD_LECTURERS_LIST = 'ASYNC_LOAD_LECTURERS_LIST';
export const ASYNC_DELETE_LECTURER = 'ASYNC_DELETE_LECTURER';
export const SYNC_LECTURERS_LIST_SEARCH_PARAMS = 'SYNC_LECTURERS_LIST_SEARCH_PARAMS';
export const ASYNC_LOAD_PROVIDES = 'ASYNC_LOAD_PROVIDES';
export const ASYNC_ADD_LECTURER = 'ASYNC_ADD_LECTURER';
export const ASYNC_GET_LECTURER = 'ASYNC_GET_LECTURER';
export const ASYNC_EDIT_LECTURER = 'ASYNC_EDIT_LECTURER';
export const AYSNC_LOAD_LEVELS = 'AYSNC_LOAD_LEVELS';

