export const ASYNC_LOAD_LECTURERS_LIST = 'ASYNC_LOAD_LECTURERS_LIST';
export const ASYNC_DELETE_LECTURER = 'ASYNC_DELETE_LECTURER';
export const SYNC_LECTURERS_LIST_SEARCH_PARAMS = 'SYNC_LECTURERS_LIST_SEARCH_PARAMS';
