export const ASYNC_LOAD_COURSE_DIRECTION_LIST = 'ASYNC_LOAD_COURSE_DIRECTION_LIST';
export const ASYNC_CREATE_COURSE_DIRECTION = 'ASYNC_CREATE_COURSE_DIRECTION';
export const ASYNC_UPDATE_COURSE_DIRECTION = 'ASYNC_UPDATE_COURSE_DIRECTION';
export const ASYNC_DELETE_COURSE_DIRECTION = 'ASYNC_DELETE_COURSE_DIRECTION';
export const ASYNC_COURSE_DIRECTION_DETAILS = 'ASYNC_COURSE_DIRECTION_DETAILS';
export const SYNC_CLEAR_COURSE_DIRECTION_DETAILS = 'SYNC_CLEAR_COURSE_DIRECTION_DETAILS';
